#!/bin/bash

cd `git rev-parse --show-toplevel`

name_status=`git diff --name-status $@`

declare -A filemap

IFS='
'
for ns in ${name_status[@]}; do
    IFS=$'\t'
    element=($ns)
    filemap["${element[1]}"]=${element[0]}
    if [[ ${element[0]} =~ ^R ]]; then
        filemap["${element[1]}"]+=":${element[2]}"
    fi
done
IFS=' '

args=()
submodules=()

while [[ $# > 0 ]]; do
    case $1 in

    --no-skip)
        noskip=1
        shift
        continue
        ;;

    --recursive)
        recursive=1
        shift
        continue
        ;;

    esac

    if [[ ! ${!filemap[@]} =~ $1 ]]; then
        args+=($1)
    fi

    shift
done

if [[ ${#args[@]} == 0 ]] || [[ ! "${args[-1]}" == "--" ]]; then
    args+=(--)
fi

for file in ${!filemap[@]}; do
    echo -en "$file ["

    status=(${filemap[$file]})

    if [[ -d $file ]]; then
        submodule="$file"
        status="S$status"
    fi

    if [[ -z "$noskip" ]] && [[ -n "$submodule" ]] || [[ ${status} == "A" ]] || [[ ${status} == "D" ]]; then
        status+=("skip")
        unset filemap[$file]
    fi

    echo "$status]"

    tempargs=()

    if [[ ${filemap[$file]} =~ ^R ]]; then
        IFS=':'
        renamedata=(${filemap[$file]})
        tempargs+=("-M${renamedata[0]:1}%")
        file=($file ${renamedata[1]})
    fi

    sleep .25

    git difftool ${tempargs[@]} ${args[@]} ${file[@]} &
    pid=$!
    if [[ -n "$submodule" ]] && [[ -n "$recursive" ]]; then
        git -C $submodule diffall ${args[@]} &
        pid=$!
    fi

    unset status submodule tempargs
done

wait $pid
